<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- 🔹 Carpetas estáticas del proyecto -->
  <ItemGroup>
    <Folder Include="wwwroot\assets\" />
  </ItemGroup>

  <!-- 🔹 Dependencias necesarias para desarrollo y compilación dinámica de vistas -->
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SistemaPOS.Application\SistemaPOS.Application.csproj" />
  </ItemGroup>

  <!-- 🔹 Referencias a capas de la solución -->

</Project>
